### PR TITLE
add some nice hover effects

### PR DESCRIPTION
**Pull request by UpTiGamer**

### CODE REVIEW

**Comment by UpTiGamer** [comment]
@M1noa @3kh0  @3kh0 @Thedogecraft

**Comment by M1noa** [comment]
Why is you pinging us put actual content dumbo

**Comment by Thedogecraft** [comment]
Hover effects are broken.

**Comment by UpTiGamer** [comment]
> Hover effects are broken.

?
works on my end have you tried githack

**Pull request closed without merging**
